### ISSUE TITLE
Provide binary path

### ISSUE THREAD

**Issue by JonathanLorimer** [neovimhaskell/nvim-hs.vim#10]
Is there any way we could just provide a path to the binary ourselves? I am using nix and stack can't build within the nix store.

**Comment by saep** [comment]
You can start your plugin binary with `jobstart()` or `rpcstart()` from within neovim or externally and connect to one of neovim's sockets.

**Comment by saep** [comment]
If started from within neovim, you need to pass `-e`, so that your plugin connects to neovim via `$NVIM_LISTEN_ADDRES`. You also need to provide a name argument (Name of your executable should do).

**Comment by JonathanLorimer** [comment]
so something like `jobstart("my-nvim-hs-plugin-binary -e")`? Thanks for the quick response btw!

**Comment by saep** [comment]
Closer to: `jobstart("my-nvim-hs-plugin-binary -e my-nvim-hs-plugin-binary")`

> my-nvim-hs-plugin-binary --help 

To see available arguments.

**Comment by JonathanLorimer** [comment]
If I call this function https://github.com/neovimhaskell/nvim-hs.vim/blob/develop/autoload/nvimhs.vim#L20-L56 after running `jobstart()` is that safe? Or will it try and install with stack? I am getting an issue now that no host named `my-nvim-hs-plugin-binary` is registered.

**Comment by JonathanLorimer** [comment]
can I just call `call remote#host#Register(a:name, '*', l:Factory)` ? I know l:Factory is supposed to pass the host-info, but not sure how to get that.

**Comment by saep** [comment]
I've set this up years ago. But from quickly looking through the source of `remote#host#Register()`, you call it with a name of your chosing (I'd chose the binary name), some pattern I don't understand (`'*'` probably) and a channel (i.e.the return value of `jobstart()`). Instead of the factory, you can also use the factory datatype, but that's more involved.

**Comment by JonathanLorimer** [comment]
things are closer, just getting this error:
```
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#notify:
line    6:
E475: Invalid argument: Channel doesn't exist
```
I guess the channel isn't returned from jobstart(), or I am doing something wrong.

**Comment by JonathanLorimer** [comment]
whoops, forgot to enable rpc!

**Comment by JonathanLorimer** [comment]
Things still don't seem to be working, I am guessing it might have something to do with not passing the current working directory?

**Comment by JonathanLorimer** [comment]
Anyways, thanks for all your help this far. Things aren't exactly working. This is what I have so far, if you see anything obviously wrong I would appreciate feedback https://github.com/JonathanLorimer/cornelis/blob/master/ftplugin/agda.vim#L2-L6

**Comment by saep** [comment]
I've played around with it and this works for me:

```viml
call remote#host#Register('my-nvim-hs', '*', rpcstart('my-nvim-hs', []))
```

**Comment by saep** [comment]
> which my-nvim-hs 

`/home/saep/.local/bin/my-nvim-hs`

**Comment by JonathanLorimer** [comment]
Thanks @saep that worked! I was using `jobstart()` instead of `rpcstart()` because the neovim docs suggest `rpcstart()` is deprecated. I appreciate your attentive help!

**Comment by saep** [comment]
With `jobstart` it works like this:

```viml
call remote#host#Register('my-nvim-hs', '*', jobstart(['my-nvim-hs'], {'rpc': v:true}))
```
