### ISSUE TITLE
Duplicate tag "nvim-hs"

### ISSUE THREAD

**Issue by teto** [neovimhaskell/nvim-hs.vim#6]
while trying to build this plugin, there was an error while generating the help:
`E154: Duplicate tag "nvim-hs" in file /nix/store/8hskf9qs40h426hbyxgvxkjrxhlk6nzi-vimplugin-nvim-hs-vim-2019-01-05/share/vim-plugins/nvim-hs-vim/doc/nvim-hs.txtFailed to build help tags!`

**Comment by saep** [comment]
I cannot reproduce the error, what are you doing to "build" this plugin?
Anyhow, I may have pushed a fix to master.

**Comment by teto** [comment]
that fixed it thanks
