### ISSUE TITLE
Having Trouble Getting Started

### ISSUE THREAD

**Issue by smolck** [neovimhaskell/nvim-hs.vim#7]
Hello! I'd like to develop a plugin with this and `nvim-hs`, but I'm having some trouble getting the minimal setup working. Here are the steps to reproduce what I'm running into:

1. Add `Plug 'neovimhaskell/nvim-hs.vim` to `$XDG_CONFIG_HOME/nvim/init.vim`
2. Run `:PlugInstall` from within Neovim
3. Run `$ cd $XDG_CONFIG_HOME/nvim && stack new my-nvim-hs https://raw.githubusercontent.com/neovimhaskell/nvim-hs/master/stack-template.hsfiles --bare --omit-packages --ignore-subdirs`

After following those steps, I get this error whenever I open Neovim:
```
Error detected while processing function nvimhs#start[2]..<SNR>23_readCachedBinPaths:
line    9:
E605: Exception not caught: broken cached binary path file
Error detected while processing function nvimhs#start:
line    2:
E171: Missing :endif
```

Any idea why that's happening?

**Comment by saep** [comment]
I did the same thing and it works fine for me. The command selected the resolver lts-14.27
 
The plugin basically calls does two things for you:
1. It calls `stack build` in `$XDG_CONFIG_HOME/nvim`
2. It runs `$(stack path --local-install-root)/bin/my-nvim-hs`

If you execute the 2nd step, it should look this:

```
λ ~/.config/nvim/ master* `stack path --local-install-root`/bin/my-nvim-hs
�nvim_get_api_info^C
```

You can also add command line options to the script, you can list the available ones with:

```
λ ~/.config/nvim/ master* `stack path --local-install-root`/bin/my-nvim-hs --help
Start a neovim plugin provider for Haskell plugins.

Usage: my-nvim-hs [NAME] [-a|--host HOSTNAME] [-p|--port PORT] [-u|--unix ARG]
                  [-e|--environment] [-l|--log-file ARG] [-v|--log-level ARG]
  This is still work in progress. Feel free to contribute.

Available options:
  -h,--help                Show this help text
  NAME                     Name that associates the plugin provider with neovim.
                           This option has only an effect if you start nvim-hs
                           with rpcstart()/jobstart() and use the factory method
                           approach. Since it is extremely hard to figure that
                           out inside nvim-hs, this option is assumed to used if
                           the input and output is tied to standard in and
                           standard out.
  -a,--host HOSTNAME       Connect to the specified host. (requires -p)
  -p,--port PORT           Connect to the specified port. (requires -a)
  -u,--unix ARG            Connect to the given unix domain socket.
  -e,--environment         Read connection information from
                           $NVIM_LISTEN_ADDRESS.
  -l,--log-file ARG        File to log to.
  -v,--log-level ARG       Log level. Must be one of: DEBUG INFO NOTICE WARNING
                           ERROR CRITICAL ALERT EMERGENCY
```

The template installs a little vim-script that is called when you start `nvim`: `$XDG_CONFIG_HOME/nvim/plugin/nvim-hs.vim`
This executes the 2nd step. You can add logging to that like this:

```viml
call nvimhs#start(expand('<sfile>:p:h:h'), 'my-nvim-hs', ['--log-file', '/tmp/nvim-hs.log', '--log-level', 'DEBUG'])
```

If you get the help text, but no log file, then there is an issue in the vim-script. :S 

Instead of the vim-script, you can try the old manual way, to start a plugin host:

```if has('nvim') " This way, you can also put this in your plain vim config

	" function which starts a nvim-hs instance with the supplied name
	function! s:RequireHaskellHost(name)
		" It is important that the current working directory (cwd) is where
		" your configuration files are.
		return jobstart(['stack', 'exec', 'my-nvim-hs', a:name.name], {'rpc': v:true, 'cwd': expand('$HOME') . '/.config/nvim'})
	endfunction

	" Register a plugin host that is started when a haskell file is opened
	call remote#host#Register('haskell', "*.l\?hs", function('s:RequireHaskellHost'))

	" But if you need it for other files as well, you may just start it
	" forcefully by requiring it
	let hc=remote#host#Require('haskell')
endif
```

**Comment by smolck** [comment]
Thanks for the help and quick reply! The first part, with building and running the executable, works fine for me.

Running `:call nvimhs#start(expand('<sfile>:p:h:h'), 'my-nvim-hs', ['--log-file', '/tmp/nvim-hs.log', '--log-level', 'DEBUG'])` gives me this error though: 

`Failed to execute (cwd: ): git rev-parse HEAD`

I'm using nvim nightly btw if that matters.

**Comment by saep** [comment]
Oh. The script assumes you're running from a directory managed by git... I did some shenanigans for change detection based on git commit hashes to speed up the startup time of plugins. 

Work around should be to simply do a `git init` in  `$XDG_CONFIG_HOME/nvim`.

This startup helper script should obviously also work if not run from a git repository (although it will most likely be run in one). I'll fix that if I have a bit more spare time.

**Comment by smolck** [comment]
@saep Ah okay, gotcha. But even after doing `git init` things still didn't work, I was still getting that error after opening Neovim, which was resulting from this error with running `$ git rev-parse HEAD`:

```console
Failed to execute (cwd: /home/smolck/.config/nvim): git rev-parse HEAD

fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
```
However, this diff seems to fix the issue for me:
```diff
diff --git a/autoload/nvimhs.vim b/autoload/nvimhs.vim
index 286409d..89ee15d 100644
--- a/autoload/nvimhs.vim
+++ b/autoload/nvimhs.vim
@@ -87,7 +87,7 @@ endfunction
 function! nvimhs#gitCommitHash(directory)
 	return join(
 				\ nvimhs#execute(a:directory,
-				\   { 'cmd': ['git', 'rev-parse', 'HEAD'] })
+				\   { 'cmd': ['git', 'rev-parse', '--', 'HEAD'] })
 				\ , '')
 endfunction
 
@@ -250,7 +250,7 @@ function! s:buildStartAndRegister(pluginHost, host_info)
 					\                , [a:pluginHost, l:cached]
 					\                )
 
-		let l:testAndBuild = { 'cmd': ['git', 'rev-parse', 'HEAD']
+		let l:testAndBuild = { 'cmd': ['git', 'rev-parse', '--', 'HEAD']
 					\        , 'nextStep': l:IfHashDiffers
 					\        }
 		call nvimhs#executeAsync(a:pluginHost.cwd, l:testAndBuild)
```
After doing that I can use call `:echo NextRandom()` defined in the example just fine.

**Comment by saep** [comment]
`git rev-parse -- HEAD` hides the error and doesn't do anything useful.

```
λ ~/src/nvim-hs.vim/ develop git rev-parse HEAD
5bc177a87c9575c4995df90a098d330fe6e02f75
λ ~/src/nvim-hs.vim/ develop git rev-parse -- HEAD
--
HEAD
```
For `git rev-parse HEAD` to work, the repository also needs a commit. (I just tested that.)

A proper fix is to invoke the build command if the commit hash cannot be determined.

**Comment by smolck** [comment]
> git rev-parse -- HEAD hides the error and doesn't do anything useful.

Ah okay, gotcha.

> For git rev-parse HEAD to work, the repository also needs a commit. (I just tested that.)

Yup, that works! Thank you!

**Comment by saep** [comment]
The script no longer requires the plugin to be in a git repository.
