### ISSUE TITLE
Share instance of plugin between buffers?

### ISSUE THREAD

**Issue by isovector** [neovimhaskell/nvim-hs.vim#9]
I am writing an Agda plugin, with the following plugin structure:

```viml
" ftdetect/agda.vim
au BufNewFile,BufRead *.agda setf agda
au BufNewFile,BufRead *.lagda setf agda
```

and

```viml
" ftplugin/agda.vim
call nvimhs#start(expand('<sfile>:p:h:h'), 'cornelis', ['-v', 'DEBUG', '-l', '/tmp/cornelis.log'])
```

The resulting plugin gets invoked for each `.agda` buffer I open, but life would be much easier on the plugin side to reuse the same instance for each buffer. Is this possible to do?

**Comment by saep** [comment]
The first argument (in your case 'cornelis') should name a plugin instance and share it across the same neovim instance.

I've pushed a fix to master: https://github.com/neovimhaskell/nvim-hs.vim/commit/d4a6b7278ae6a1fdc64e300c3ebc1e24719af342

**Comment by isovector** [comment]
Thanks for the fast turnaround! nvim-hs has been a true joy to use!
